server:
  port: 8086

spring:
  application:
    name: recipe-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://mongo:27017/kuanto_recipes
      database: kuanto_recipes

mongock:
  migration-scan-package: recipe_service.migration
  transaction-enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true